### ISSUE TITLE
implement connection redirects for vertx-cluster

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-redis-client#106]
see: https://redis.io/topics/cluster-tutorial

Currently we fail with:

```
io.vertx.core.impl.NoStackTraceThrowable: MOVED 5355 XX.XXX.XXX.XXX:6379
```

**Comment by pendula95** [comment]
Any estimate on this issue and the timing? It is a really big issue.

**Comment by pendula95** [comment]
Thank you for the information. As I can read from the blog post "if there is some demand for it". 
There are only few good redis connectors out there. Most of theme don't support  clustering.
Most of theme are really bad and we are currently using vertx as a bridge between components with bad redis connectors (syslog-ng as example). So we are doing HTTP -> vertx -> redis. But we are facing difficulties as redis is single threaded and a single instance can not take the load that we are facing. So we are moving to cluster in order to support our needs but ATM vertx can not follow.
I think there is great need, especialy is someone is using vertx + redis in a serious production environment.

**Comment by pmlopes** [comment]
@pendula95 if you're interested in help I'm all for it, for example, my redis cluster setup skills are very limited (to the simple tutorials you can google) so if you could help setting up a cluster for the tests would be already a good step. For example this is where I setup the sentinel setup for tests https://github.com/vert-x3/vertx-redis-client/blob/d6a42159cdedf16c7e99efbcbe116c5a12f9122f/src/test/java/io/vertx/test/redis/AbstractRedisSentinelBase.java , if you could create something for cluster I'd appreciate it.

**Comment by pendula95** [comment]
Yes, I am really happy to help. Unfortunately it looks like the Embedded Redis does not support Redis cluster. Any suggestion how to handle this. Maybe use testcontainers to make Docker containers in order to form a cluster?

**Comment by artem-zinnatullin** [comment]
I think testcontainers is reasonable, you can form a Redis cluster in same container btw, just run multiple Redis instances on different ports

**Comment by pmlopes** [comment]
New client sentinel should do this
