### ISSUE TITLE
Which RedisClient and RedisOptions is the right one to use?

### ISSUE THREAD

**Issue by jlove-nz** [vert-x3/vertx-redis-client#139]
### Version

* vert.x core:  3.7.0
* vert.x redis client:  3.7.0

### Context

It isn't clear which RedisOptions class should be used, or whether io.vertx.redis.client.Redis or  io.vertx.redis.RedisClient should be used.

Based on the documentation from vertx.io (http://vertx.io/docs/vertx-redis-client/java/), it would appear that the classes in io.vertx.redis.client should be used when developing a connection to Redis, however it's very confusing as a user to choose between io.vertx.redis.X and io.vertx.redis.client.X

I think it would be helpful to document at either vertx.io or in the code itself the purpose of the different classes if it could be made clear their purpose in comparison to one another.

**Comment by javenwang** [comment]
I think we should use `io.vertx.redis.client.Redis` which is newer API.
also see #150 , and [release note](https://vertx.io/blog/eclipse-vert-x-3-7-0-released/#vert-x-redis-client)

**Comment by pmlopes** [comment]
@jlove-nz @javenwang yes `io.vertx.redis.client.Redis` is the right one as the old code is to be removed on 4.0 (master). Since this code isn't fully on par with the old one we currently have the 2 APIs available.

Once the connection pool gets implemented (which will offer better connection management than the old implementation then the old code is to be removed from a release.

**Comment by jlove-nz** [comment]
@pmlopes Thanks for the update. I'll look forward to 4.0.
