### ISSUE TITLE
Cluster: SLOTS No client's available.

### ISSUE THREAD

**Issue by wbkys** [vert-x3/vertx-redis-client#146]
### Context

localhost vert.x 192.168.0.2
redis cluster  192.168.0.10,192.168.0.11,192.168.0.12
connect......
Apr 13, 2019 2:30:01 PM io.vertx.redis.client.impl.RedisClusterClient
WARNING: Failed to connect to: 192.168.0.10:6300
WARNING: Failed to connect to: 192.168.0.11:6300
WARNING: Failed to connect to: 192.168.0.12:6300

onConnect.cause().getMessage():-> SLOTS No client's available.

### Do you have a reproducer?

* Link to github project/gist

### Steps to reproduce

final RedisOptions options = new RedisOptions()
      		  .setType(RedisClientType.CLUSTER)
    		  .setEndpoints(hosts)
.setPassword(redisOptions.getString("redis_cluster_auth")).setUseSlave(RedisSlaves.NEVER);

Redis.createClient(vertx, options)
      .connect(onConnect -> {
        if (onConnect.succeeded()) {
          redis = RedisAPI.api(onConnect.result());
          log.info("redis start");
          startFuture.complete();
        }else {
        	log.error("redis error:" + onConnect.cause().getMessage());
                //SLOTS No client's available.
        }
      });

### Extra

* Anything that can be relevant
redis cluster  on localhost is right,
redis cluster  on other ip is wrong.

**Comment by wbkys** [comment]
![image](https://user-images.githubusercontent.com/12574291/56075755-38f07280-5dfa-11e9-918a-841cae26c527.png)

**Comment by pmlopes** [comment]
@wbkys your config ip addresses does not seem to match what the first node is configured, you don't need to specify all hosts in the config, the first one that the client connects to, will return the cluster information, so:

You say:

* 192.168.0.10
* 192.168.0.11
* 192.168.0.12

But Redis says:

* 192.168.0.181
* 192.168.0.182
* 192.168.0.183

Can you double check your setup?

**Comment by wbkys** [comment]
Sorry, screenshot problem.
But the problem is as I said, please ignore the screenshot.

**Comment by pmlopes** [comment]
So the problem is that all your nodes are password protected? and the discovery is attempting to connect without password?

**Comment by wbkys** [comment]
Yes,All passwords will fail

**Comment by jlove-nz** [comment]
Just to add a note to this issue.

Following the guide https://tgrall.github.io/blog/2019/09/05/multi-nodes-redis-cluster-with-docker/ and having run two (not three, unsure if this matters) redis nodes, I have a Redis cluster which "appears" to work.

I say "appears" because not knowing Redis that well, I would connect to a master node, and be able to use the cluster, but connecting to a slave node and attempting to run any command would kill the connection instantly.

In any case, I forged on and attempted to use a simple vertx Redis connection with the configuration:

```
"connection": {
          "type": "CLUSTER",
          "useSlave": "NEVER",
          "endpoints": [
            "127.0.0.1:12000",
            "127.0.0.1:12001",
          ]
        }
}
```

This configuration allowed VertX to connect to the cluster, however the connection would immediately fail with "SLOTS No client's available"

I had no luck in attempting to resolve this. I did however note that I could not run `CLUSTER SLOTS` from `redis-cli` connections to either node. Against the slave node it would immediately disconnect. Against the master node it would complain about not having authorisation to run the command.

Having failed to achieve connectivity with docker based redis connections, I swapped to simply running Redis in a cluster on the localhost - using https://redis.io/topics/cluster-tutorial as a guide. This worked perfectly.

Given the above, I suspect that the RedisLabs docker container setup is such that `CLUSTER SLOTS` is not allowed to be run, and this in turn breaks the ability for VertX to connect successfully.

**Comment by pmlopes** [comment]
@jlove-nz can you give it a shot with the latest release candidate `4.0.0-milestone4` lots of fixes are on that rc, which might solve this.

On a side note, all tests for this module run on a redis cluster using this image:

```
docker pull grokzen/redis-cluster:latest
docker run -d -e 'IP=127.0.0.1' -e 'STANDALONE=true' -e 'SENTINEL=true' -p '7000-7007:7000-7007' -p '5000-5002:5000-5002' grokzen/redis-cluster:latest
```

It could be that the config is wrong and lots of wrong assumptions were made and I haven't read that link yet.

**Comment by pmlopes** [comment]
Passwords are now inherited from the parent connection and fall back to the default password on options.
