### ISSUE TITLE
RedisOptionsConverter do not have parser for endpoint key

### ISSUE THREAD

**Issue by glassfox** [vert-x3/vertx-redis-client#147]
Hi guys,
After 3.7.0 upgrade I found several issues:
1. In old RedisClient added restriction for "auth" and "select" keys. This throw in my case "connection refused" exception. (maybe set actual values only if exist)

[https://github.com/vert-x3/vertx-redis-client/blob/22c69ed7eb1047a7cfb6e441cf286d74ccb81007/src/main/java/io/vertx/redis/impl/RedisClientImpl.java#L119-L123](https://github.com/vert-x3/vertx-redis-client/blob/22c69ed7eb1047a7cfb6e441cf286d74ccb81007/src/main/java/io/vertx/redis/impl/RedisClientImpl.java#L119-L123)

2. New RedisOptions do not backward compatible with old RedisOptions, this will required a lot of configuration changes. (maybe jsonparser need to be more smarter)

3. New RedisOptions do not parse "endpoints" from/to JsonObject. -> this is critical.

**Comment by wbkys** [comment]
+1

**Comment by ben-r** [comment]
+1

This is indeed critical and I currently don't know how to configure endpoints since it's always working with the default value `127.0.0.1:6379`.

Also how the client creation works is really strange since you are forced to convert the `RedisOptions` to an `JsonObject` which is internally converted back. Why?
