### ISSUE TITLE
_buffer in ReplyParse is not emptied at the end of the reply

### ISSUE THREAD

**Issue by imavroukakis** [vert-x3/vertx-redis-client#20]
I was doing some profiling on an application and I noticed several instances of rather large `byte[]` arrays that aligned with the size of the object that I was retrieving from redis in `ReplyParse`. Here's a screenshot from the profiler.

![image](https://cloud.githubusercontent.com/assets/1764981/8505408/745c4e88-21dc-11e5-9a47-c974aa91347d.png)

Is it a conscious decision not to reset `_buffer` after a full reply has been received?

**Comment by pmlopes** [comment]
No, that's a bug I think.

**Comment by imavroukakis** [comment]
Great, thought as much. The manifestation of this is mainly increased GC pressure, which detracts from performance.

**Comment by pmlopes** [comment]
The internal buffer is clear on a subsequent message, the way the parser works is if the current internal buffer length is the same as the read offset then the internal buffer is replaced with the incoming one (this works when each message is delivered in a single buffer).

When messages have been broken into smaller pieces on a subsequent message if the read offset is not 0 then the internal buffer is replaced with a copy of itself from the current read offset, it does a copy and not a slice since a slice is just a reference to the original buffer.

So the clean up is not imediate, but it does happen :)
