### ISSUE TITLE
RedisClientImpl - handlePubSubMessage is not using address from options

### ISSUE THREAD

**Issue by lukjel** [vert-x3/vertx-redis-client#214]
There is a code (156):
```
final String vertxChannel = BASE_ADDRESS + "." + channel;
```

in my opinion, it should look like:
```
final String vertxChannel = this.options.getAddress() + "." + channel;
```

**Comment by pmlopes** [comment]
`address` was the _wrong_ name for `endpoint`. The address was how we used to refer to the redis connection string, e.g.: `redis://localhost/1`. Now that redis has a fully recognized rfc to identify the schemas: `redis` and `rediss` and the official documentation names these `endpoints` the option object refers now to them as `endpoint`.

So this issue was a misunderstanding of the API and will be closed.
