### ISSUE TITLE
RedisClient: PubSub not using configured address

### ISSUE THREAD

**Issue by underkin** [vert-x3/vertx-redis-client#217]
### Description

There is an issue on 3.8 code base.
PubSub is not using the address configured when creating the client, but the DEFAULT_ADDRES

### Version

3.8.5

### Steps to reproduce

1. Create a Redis client and subscribe to any channel with a address different to io.vertx.redix
2. Subscribe to messages: vertx.eventBus().consumer (address+channel, handler)
3. Check you don't get any notification
4. Using address  io.vertx.redix it works.

**Comment by pmlopes** [comment]
In 4.0.0 we're letting users decide what to do on `push` messages. Instead of "forcing" the eventbus a `handler` is expected to be provided to do this. As a user you can either send it over the eventbus or handle in any other way. For the cases where eventbus is not needed, this has the benefit that it reduces the latency and gc and messages don't need to be encoded/decoded several times while switching from redis to jvm to eventbus to jvm.
