### ISSUE TITLE
Support for redis over ssl

### ISSUE THREAD

**Issue by zenios** [vert-x3/vertx-redis-client#230]
Event though rediss scheme is supported it does not enable ssl.

What is required is to execute an upgradetoSSL inside RedisConnectionProvider.connect when the uri is ssl enabled.

**Comment by pmlopes** [comment]
@zenios currently we use a connection pool which hides the `netClient` instance. In order to support `ssl` we need to create the pool with `ssl` enabled. Currently this is possible in a hidden way, by setting `netClientOptions.setSSL(true)`.

Like you said, the `s` in the redis connection string is not considered atm. I think we need to be a bit pragmatic here.

When creating the connection pool (which is a one time operation for the client lifecycle) we should do:

* loop all connection strings (endpoints)
* they all must agree with the same ssl flag
* flip the flag in the options `netClientOptions` param for the user

What do you think?

**Comment by zenios** [comment]
@pmlopes netClientOptions.setSSL(true) indeed works but what if i have multiple endpoints (Some with ssl some not). This is the reason it has to be done on a per socket

**Comment by zenios** [comment]
@pmlopes  Actually i think it is possible. If i am not mistaken, 

https://github.com/vert-x3/vertx-redis-client/blob/01605b8efd30e027460514cc1a6cfd762c42c038/src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java#L109

Here we should check if redisURI.socketAddress() is ssl then updateToSSL

**Comment by pmlopes** [comment]
then the connection pool doesn't fit our needs as we need 2 modes and we can't change the `netClient` ssl flag once it's created if i'm not mistaken.

Also I never heard of such setup (although possible, of course), would someone use a mix or ssl and non ssl connections on a cluster/sentinel mode?

**Comment by pmlopes** [comment]
@tgrall you know a bit of redis right :wink: ? what are the usual cases for `redis` cluster/sentinel `ssl` usage? do you even see them mixed together?

Also in cluster mode, when a query fails and the server returns a `MOVED` response, I belive you only get, the `bucket`, `ip address` and `port`. There's no info if it's `ssl`, right?

**Comment by zenios** [comment]
@pmlopes i have the impression that a single net client can support both connections (Either ssl or not)

once the netSocket is connected if upgradeToSsl is called then an ssl handler is added  to the pipeline

sql-client does the same

**Comment by pmlopes** [comment]
@zenios you're right! I've just checked with Julien. we can start the pool without `SSL` and upgrade the socket on a per use case basis.

So this is a cleaner approach that solves the case where all server endpoints are known. Still to identify/handle is the case where a cluster is connected without the full node knowledge, in that case, the redis response is incomplete.

**Comment by zenios** [comment]
Cluster

When Redis Cluster is used, use tls-cluster yes in order to enable TLS for
the cluster bus and cross-node connections.


This is from redis.i assume if a cluster is ssl enabled then all nodes
should be ssl enabled as well

**Comment by pmlopes** [comment]
Ok, then we can use the current connection ssl state to connect to the new node.

**Comment by pmlopes** [comment]
So, so sum up the current thread:

1. create a connection pool as usual
2. on connection creation, perform `startls` handshake if needed (consider the pool, netclient config and the given redis url)
3. downgrade is not allowed (over complicates the logic), in such cases users are advised to not set `ssl` on the `netClientOptions`.

On cluster mode, doing a reconnect will take the ssl state from the current connection that got the `ASK` response.

**Comment by zenios** [comment]
1. `if needed` will be according to the scheme right?
2. What do you mean by downgrade? Each netSocket is binded to a url (redis:// or rediss://). When can a url change scheme in order to downgrade?

**Comment by pmlopes** [comment]
@zenios by if needed I wanted to say:

If a user set the flag `ssl` on net client options and the connection is: `rediss` the no need to upgrade, the default connection is already ssl.

By no downgrade, I mean, if again the user sets `ssl` on the net client options a request with `redis://` shall fail as by default the pool is operating in ssl mode.

To explain even further, we can't just ignore the `ssl` flag, because power users may want to validate certificates and tune the ssl connection, which isn't possible just with the connection string. For most users the connection string shall be enough as they don't tweak the net client options and by default the pool is always created in non ssl, so upgrades are always possible.

I'm trying to safeguard for the edge cases, just in case :wink:

**Comment by zenios** [comment]
> To explain even further, we can't just ignore the ssl flag, because power users may want to validate certificates and tune the ssl connection, which isn't possible just with the connection string. For most users the connection string shall be enough as they don't tweak the net client options and by default the pool is always created in non ssl, so upgrades are always possible.

Actually you can set all the ssl options without enabling ssl and they will be used when upgrading

but yes you are right. If someone forces ssl on NetOptions then redis:// should not be accepted. It would be good to throw an exception that explains these case (If and when happens)
