### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by aomsweet** [vert-x3/vertx-redis-client#272]
### Version

Java: 11
Quarkus: 1.10.5.Final
Vertx: 3.9.5
Vertx-redis-client: 3.9.5

Java command line:  `nohup java -Xms2048m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true -jar provider-web-jl-1.0-SNAPSHOT-runner.jar &`

### Context

Deploy on cloud server, OutOfMemoryError will occur about every two days.
The picture is a screenshot of jvm dump.

![image](https://user-images.githubusercontent.com/70388114/103195999-517e2480-491e-11eb-8f00-b1e4f0cf8cf0.png)

**Comment by pmlopes** [comment]
@aomsweet It is unclear from the image where the leak is happening. To reduce the amount of buffers, the parser passes slice references to the user code, so the leak could be happening because either the parser is incorrectly holding a reference to them, or the client code is.

In order to properly look this up, can you prepare a small project and instructions, say for example, force the `Xmx` to a small value say `128M` that triggers the OOM.

**Comment by pmlopes** [comment]
@aomsweet Also can you try this out with `4.0.0`?

**Comment by pmlopes** [comment]
Closing as there seems to be no more activity on this issue. Re-open if needed.
