### ISSUE TITLE
Cluster Pool Size Error

### ISSUE THREAD

**Issue by orxelm** [vert-x3/vertx-redis-client#274]
Hi
The validation agains the maxPoolSize as described in the link, should be done agains the number of endpoints rather than the number of slots. The reason is that the number of slots can be larger than the number of nodes.
https://github.com/vert-x3/vertx-redis-client/blob/c2eeb3d3c322b3369d3a600149c1591e762fdce1/src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java#L164

**Comment by pmlopes** [comment]
@orxelm I'm not sure that would be correct. We can define a single `endpoint` to create a cluster connection, the expected behavior is to fetch all the slots from that endpoint connection and we must connect to all nodes. The reason is that it's the client responsibility to send commands to the right node. For example given a key, using it's zmodem hash it needs to be sent to the right node. Also it needs to take into consideration is it's a read or write node.

I may be wrong thought :) perhaps the best is if you can describe an example setup and when the number of nodes would not be correct.

**Comment by orxelm** [comment]
@pmlopes Thanks for the quick response.
See here: https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java#L168

After the call for slots command, you get the cluster endpoints and connect them one by one.
This is the place where you know the number of nodes in the cluster, so i think this is the place you should validate them agains the maxPoolSize. What do you think?
