### ISSUE TITLE
Eval not returning object type of result

### ISSUE THREAD

**Issue by alanma** [vert-x3/vertx-redis-client#30]
In Jedis client, Eval op will return Object. But in redis-client here we return nothing with a void type. Any specific reason that we could not return object type? I could work on a PR if we want the eval and eval sha to be able to return object type data.

Thanks.

**Comment by pmlopes** [comment]
We do not use jedis and due to the fact that we use codegen to generate the polyglot API there is no possibility to declare that the return is os type Object. We need to extend the API to have probably the following method:

evalLong, evalString, evalArray plus the same for evalSha where we explicitly declare the return type on the method signature.

**Comment by pmlopes** [comment]
After discussing with the team we can create a single `eval` that always returns an redis Multi, in case the return is a Bulk or a Number we wrap it in a single element Multi

**Comment by pmlopes** [comment]
@alanma could you make a review to PR #32 .
