### ISSUE TITLE
Redis client reconnect fails without AUTH

### ISSUE THREAD

**Issue by alanma** [vert-x3/vertx-redis-client#31]
@pmlopes 

My redis server has AUTh required. So when I initialize my redis client, I have to manually call AUTH command after creating the redis client. Now I am seeing my redis-client losing connection to my redis server - not sure why yet - but reconnecting to the redis server does not call AUTH command. Therefore, queued commands won't be able to run after trying reconnecting with the exception:

`NOAUTH Authentication required.`

How should we reconnect to redis server requiring AUTH? I'd think we should call AUTH commands in the connect function in the RedisConnection class. Thoughts?

Thanks.

**Comment by pmlopes** [comment]
This is a feature that was not backported from the old redis client. Basically the old client connect call did 3 things:

* connect
* issue `auth` command if auth is in use
* issue `select` if select command was in use

This was making the assumption that no commands would be issued in between and that once authenticated or desired db was selected those values would not change. To my view the proper way is to have a `connectHandler` where the user has full control of what happens once a connection is established. I think we need to add an extra method:

```java
RedisClient connectHandler(Handler<AsyncResult<Void>> connect)
```

Which should be called once a socket connection is established to the redis server.
```

**Comment by alanma** [comment]
@pmlopes making perfect sense to me with the connectHandler. thanks again.

**Comment by pmlopes** [comment]
I did start by implementing this for the PR that is linked to this issue, however this solution has a shortcoming which is that due to the async nature of the code i have no knowledge when the connectionHandler code is complete and its final state. Without knowing this i cannot keep the queue of commands to retry on connection loss (since i can only retry after the handler is complete and successful).

Given this the PR implements the more conservative solution, which is user must suply and auth and/or select at config time and those values are used on every connect.

**Comment by listaction** [comment]
this is still happening with 3.5.1 @ajaysarda
