### ISSUE TITLE
master slave configuration / amazon elasticache

### ISSUE THREAD

**Issue by PatrickSauts** [vert-x3/vertx-redis-client#44]
How do you configure vertx-redis-client for master slave configuration / amazon elasticache?

**Comment by pmlopes** [comment]
This is a pure redis config question not a issue.

I think all you need to do is that on your slave you need to issue the command:

````
slave of IP PORT
````

where IP and PORT are the ip and port of the master, now from you code just connect as usual.

**Comment by PatrickSauts** [comment]
Well I believe it's a litle bit more than that, because of java dns caching and the way amazon re-elect a master.

For example redisson add to fix it https://github.com/mrniko/redisson/issues/165

**Comment by pmlopes** [comment]
The issue is with DNS, if caching is a problem that should be addressed at https://github.com/eclipse/vert.x because we build the redis protocol on top of it and we do not do anything low level like DNS in our code. If this turns to be an issue (i cannot confirm it because i have no test or a free AWS account) then let us know in the core project,
