### ISSUE TITLE
Redis pipeline

### ISSUE THREAD

**Issue by renatolond** [vert-x3/vertx-redis-client#47]
Hello!
Redis supports commands sent in a pipeline. This reduces network traffic as well as turns some commands into a sort of commit block. Is there any plans to implement a pipeline?

**Comment by pmlopes** [comment]
This is how the implementation works: the implementation follows the spec: http://redis.io/topics/pipelining

**Comment by renatolond** [comment]
Sorry if I wasn't clear, in some implementations, like jedis, you can explicitly open a pipeline, ensuring that a couple of commands will be necessarily sent in a block. (https://github.com/xetorthio/jedis/wiki/AdvancedUsage#pipelining)
As far as I've seen, there is no way to do something like that in vertx-redis-client, is there plans to implement something like this? Or am I missing it?

**Comment by pmlopes** [comment]
As i wrote the implementation only works in pipeline mode, so if you do something like:

```java
for(int i = 0; i < 10; i++) {
  redis.set("mykey", i, res -> {});
}
```

and if you would see what is happening at the  network level you would see that in one TCP connection the client writes:

```
SET mykey 0
SET mykey 1
SET mykey 2
SET mykey 3
SET mykey 4
SET mykey 5
SET mykey 6
SET mykey 7
SET mykey 8
SET mykey 9
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
```
And then the responses start coming back (probably interleaved with the writes) and get delivered to the correct handler.

Vert.x redis client was implemented from scratch to work in pipeline since that is the way redis server works. Other drivers did not implement this from start (like jedis) so they created this "pipeline" mode later on, we vert.x have it as the core of the protocol since the beginning and you do not need to do anything to use it.

**Comment by telecoder** [comment]
In the redis documentation they use an example where 10k commands are pipelined so they are send at the same time, then the client wait for the replies.

From your example it looks like the amount of redis commands that use the pipeline is not configurable or predicted.

How the vertx redis client exactly behaves?

**Comment by pmlopes** [comment]
it is an unbounded list at the moment, it grows as long as you have memory. Of course there is room for improvement here, if you think we should have a configurable limit, please open a new issue and discuss what should be the sensible default, what should be the behavior when the commands in the queue go over this value, etc...
