### ISSUE TITLE
RedisConnection state corrupted by connection RST

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-redis-client#65]
The `RedisConnection` update its state when it handles an exception because buffers could still be in the `NetSocket ` and delivered which corrupt the state of the `RedisConnection`.

Change it to only close the `NetSocket ` and perform this state update in the `NetSocket#closeHandler` when we are sure no buffer event will be delivered.

**Comment by oli-h** [comment]
I know it's already closed - but we stick on Vertx 3.3.3 for differetn reasons and think that we now observerd this issue too in our project in our production environment.
_Note: We use https://github.com/swisspush/gateleen, https://github.com/swisspush/vertx-rest-storage and https://github.com/swisspush/vertx-redisques_
We observed
- RedisClient has no TCP-Socket any more to Redis - and also vice vera: Redis sees no client connection.
- RedisClient still accepts commands (without excecptions and without calling error handlers)

We tried to reproduce it (kill Redis instance while RedisClient is connected etc) - but no luck.
Can you please shortly explain:
- are our observations (no Socket - still accepting Redis commands) related to this issue here?
- What is the sequence (TCP packets, TCP_RST, Handler calls etc...) to get RedisClient in this 'corrupt state'?
- What is the content of the attributes 'state' and 'waiting' (in RedisConnection.java) to be in the 'corrupt state'?

Thanks for some clarifying words.
