### ISSUE TITLE
flush(all|db)async commands

### ISSUE THREAD

**Issue by andre2i** [vert-x3/vertx-redis-client#86]
### Version

* vert.x core: all
* vert.x redis client: all

### Context

Are there any plans to support the natively non-blocking versions of the flush commands? They are supported by Redis >4.0? See https://redis.io/commands/flushall#codeflushall-asynccode-redis-400-or-greater

**Comment by pmlopes** [comment]
Short answer yes. Long answer we need to sync to the 4.x API and the resources are scarce. Would you like to volunteer?

**Comment by andre2i** [comment]
Hi Paulo, that sounds interesting. Can you give me some details about the amount of work involved?

**Comment by pmlopes** [comment]
Last time I've sync'ed the API it was for 3.2.1, my process if as follows:

1. Download: https://redis.io/commands.json
2. look up all API's that are older than 3.2.1
3. define the new API on https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/RedisClient.java
4. implement the API: https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/impl/RedisClientImpl.java

The implementation is a 1 line operation, there are helpers for the wire protocol so all you need is to call a `sendXXX()` method where XXX is the type of payload numeric, string, list and cast all the arguments to a buffer using the helper `toPayload()`

5. You will need to apply the same on the https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/RedisTransaction.java interface and notice that the handler returns always a string since it's a deferred execution on a bulk operation.

**Comment by andre2i** [comment]
Thanks for the details, Paulo. Sounds good. Is there a CLA for the project or does it inherit it from eclipse/vert.x? I will be going on vacation soon so I can be available to take on something like this afterwards but I'm very interested in contributing.

**Comment by vietj** [comment]
@andre2i you should sign the Eclipse CLA

**Comment by andre2i** [comment]
@vietj Is it this one? https://eclipse.org/legal/ECA.php? Should be ok, already signed that.

**Comment by pmlopes** [comment]
Yes that's the one.

**Comment by pmlopes** [comment]
The flush commands are already added, so this issue is now invalid.
